/**
 * Index-note generation — `projects/`, `labels/`, `tickets/`.
 *
 * These notes used to be stubs whose real content lived in Postgres and was
 * only ever assembled by the dashboard. With the database gone, the backlinks
 * are materialised into the markdown itself, so the same file reads correctly
 * from GitHub, Obsidian, the terminal, and by an agent with nothing but a
 * checkout.
 *
 * PURE — no IO. The caller reads the vault and writes the results.
 */

import { TYPE_FOLDER } from "./builders.js";
import type { ParsedEntry } from "./parse.js";

export type IndexKind = "project" | "label" | "ticket";

const KIND_FOLDER: Record<IndexKind, string> = {
  project: "projects",
  label: "labels",
  ticket: "tickets",
};

export interface IndexNote {
  /** Vault-relative path, e.g. "projects/voidlink.md". */
  path: string;
  kind: IndexKind;
  /** The project name / label / ticket id this note indexes. */
  ref: string;
  contents: string;
  /** Ids of the entries linking here, newest first. */
  backlinks: string[];
}

/**
 * Existing `created` stamps, keyed by vault-relative path. Regeneration reuses
 * them so a reindex doesn't rewrite the birth date of every index note — which
 * would turn a no-op run into a 50-file diff and make real changes unreadable.
 */
export type ExistingCreated = ReadonlyMap<string, string>;

/** Group entries by the refs they point at, preserving each ref's first-seen casing. */
function collect(entries: readonly ParsedEntry[]): Map<IndexKind, Map<string, ParsedEntry[]>> {
  const out = new Map<IndexKind, Map<string, ParsedEntry[]>>([
    ["project", new Map()],
    ["label", new Map()],
    ["ticket", new Map()],
  ]);

  const push = (kind: IndexKind, ref: string, entry: ParsedEntry): void => {
    if (!ref) return;
    const bucket = out.get(kind);
    if (!bucket) return;
    const existing = bucket.get(ref);
    if (existing) existing.push(entry);
    else bucket.set(ref, [entry]);
  };

  for (const entry of entries) {
    if (entry.project) push("project", entry.project, entry);
    for (const label of entry.labels) push("label", label, entry);
    if (entry.ticket) push("ticket", entry.ticket, entry);
  }

  return out;
}

/**
 * Sort newest first, falling back to id so the output is deterministic when two
 * entries share a `created` stamp (or when one is missing it entirely).
 * Determinism matters more than the tie-break rule: a non-deterministic index
 * produces phantom diffs on every run.
 */
function byNewest(a: ParsedEntry, b: ParsedEntry): number {
  if (a.created !== b.created) return a.created < b.created ? 1 : -1;
  return a.id < b.id ? 1 : -1;
}

function renderNote(
  kind: IndexKind,
  ref: string,
  entries: readonly ParsedEntry[],
  created: string,
): string {
  const lines = [
    "---",
    "type: index",
    `id: ${ref}`,
    `kind: ${kind}`,
    `title: ${ref}`,
    `created: "${created}"`,
    `count: ${entries.length}`,
    "---",
    "",
    "## Backlinks",
    "",
    "_Generated by `brain index` from entry frontmatter. Do not edit by hand — edits are_",
    "_overwritten on the next run. To change what appears here, change the entry._",
    "",
  ];

  for (const entry of entries) {
    const date = entry.created.slice(0, 10);
    const folder = TYPE_FOLDER[entry.type];
    lines.push(`- ${date} · \`${entry.type}\` · [[${folder}/${entry.id}|${entry.title}]]`);
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Build every index note implied by the entries. Refs that no longer appear in
 * any entry produce no note — the caller decides whether to delete the orphan
 * file, since deletion is IO and this module does none.
 */
export function buildIndexNotes(
  entries: readonly ParsedEntry[],
  existingCreated: ExistingCreated = new Map(),
  fallbackCreated = "1970-01-01T00:00:00-03:00",
): IndexNote[] {
  const grouped = collect(entries);
  const notes: IndexNote[] = [];

  for (const [kind, refs] of grouped) {
    for (const [ref, group] of refs) {
      const sorted = [...group].sort(byNewest);
      const path = `${KIND_FOLDER[kind]}/${ref}.md`;
      // An index note is born the day its oldest entry was, unless one already
      // exists — then its original stamp wins.
      const oldest = sorted[sorted.length - 1]?.created;
      const created = existingCreated.get(path) ?? oldest ?? fallbackCreated;

      notes.push({
        path,
        kind,
        ref,
        contents: renderNote(kind, ref, sorted, created),
        backlinks: sorted.map((e) => e.id),
      });
    }
  }

  return notes.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}

/** Vault-relative paths of index notes that exist on disk but no entry references. */
export function orphanedIndexNotes(
  existingPaths: readonly string[],
  notes: readonly IndexNote[],
): string[] {
  const live = new Set(notes.map((n) => n.path));
  const indexFolders = new Set(Object.values(KIND_FOLDER));
  return existingPaths
    .filter((p) => indexFolders.has(p.split("/")[0] ?? "") && !live.has(p))
    .sort();
}
